[package]
name = "hertz"
version = "0.1.0"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = true

[dependencies]
subprocess = "0.2.6"